from .models import MonitorProfile

DEFAULT_PROFILES = [
    MonitorProfile(
        id="elon-musk",
        display_name="Elon Musk",
        handle="elonmusk",
        pulse_symbol="TSLA",
        pulse_provider="yfinance",
        pulse_context="关联上市公司",
        category="technology",
    ),
    MonitorProfile(
        id="donald-trump",
        display_name="Donald Trump",
        handle="realDonaldTrump",
        pulse_symbol="DJT",
        pulse_provider="yfinance",
        pulse_context="关联上市公司",
        category="policy",
    ),
    MonitorProfile(
        id="justin-sun",
        display_name="Justin Sun",
        handle="justinsuntron",
        pulse_symbol="TRXUSDT",
        pulse_provider="binance",
        pulse_context="关联生态资产",
        category="crypto",
    ),
    MonitorProfile(
        id="cathie-wood",
        display_name="Cathie Wood",
        handle="CathieDWood",
        pulse_symbol="ARKK",
        pulse_provider="yfinance",
        pulse_context="旗舰 ETF",
        category="fund",
    ),
    MonitorProfile(id="ray-dalio", display_name="Ray Dalio", handle="RayDalio", category="fund"),
    MonitorProfile(
        id="michael-burry", display_name="Michael Burry", handle="michaeljburry", category="fund"
    ),
    MonitorProfile(
        id="bill-ackman", display_name="Bill Ackman", handle="BillAckman", category="fund"
    ),
    MonitorProfile(
        id="chamath", display_name="Chamath Palihapitiya", handle="chamath", category="technology"
    ),
    MonitorProfile(
        id="cz-binance",
        display_name="CZ",
        handle="cz_binance",
        pulse_symbol="BNBUSDT",
        pulse_provider="binance",
        pulse_context="关联生态资产",
        category="crypto",
    ),
    MonitorProfile(
        id="vitalik",
        display_name="Vitalik Buterin",
        handle="VitalikButerin",
        pulse_symbol="ETHUSDT",
        pulse_provider="binance",
        pulse_context="关联生态资产",
        category="crypto",
    ),
    MonitorProfile(
        id="berkshire",
        display_name="Berkshire Hathaway",
        cik="1067983",
        pulse_symbol="BRK-B",
        pulse_provider="yfinance",
        pulse_context="上市公司行情",
        category="filing",
        tags=["13F"],
    ),
    MonitorProfile(
        id="ark-invest",
        display_name="ARK Investment Management",
        cik="1697748",
        pulse_symbol="ARKK",
        pulse_provider="yfinance",
        pulse_context="旗舰 ETF",
        category="filing",
        tags=["13F"],
    ),
    MonitorProfile(
        id="market-bitcoin",
        display_name="Bitcoin",
        pulse_symbol="BTCUSDT",
        pulse_provider="binance",
        pulse_context="加密市场",
        category="market",
    ),
    MonitorProfile(
        id="market-ethereum",
        display_name="Ethereum",
        pulse_symbol="ETHUSDT",
        pulse_provider="binance",
        pulse_context="加密市场",
        category="market",
    ),
    MonitorProfile(
        id="market-sp500",
        display_name="S&P 500",
        pulse_symbol="SPY",
        pulse_provider="yfinance",
        pulse_context="美股大盘代理 ETF",
        category="market",
    ),
    MonitorProfile(
        id="market-nasdaq",
        display_name="Nasdaq 100",
        pulse_symbol="QQQ",
        pulse_provider="yfinance",
        pulse_context="美股科技代理 ETF",
        category="market",
    ),
    MonitorProfile(
        id="market-gold",
        display_name="COMEX Gold",
        pulse_symbol="GC",
        pulse_provider="futures",
        pulse_context="全球期货",
        category="market",
    ),
    MonitorProfile(
        id="market-wti",
        display_name="WTI Crude Oil",
        pulse_symbol="CL",
        pulse_provider="futures",
        pulse_context="全球期货",
        category="market",
    ),
]
